basePath: /api/v1
definitions:
  main.errorResponse:
    properties:
      error:
        type: string
    type: object
  main.handleAuthOnboarding.response:
    properties:
      id:
        type: string
    type: object
  main.handleAuthRefreshToken.response:
    properties:
      message:
        type: string
    type: object
  main.handleAuthRegister.request:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  title: Pagesy
  version: "1.0"
paths:
  /auth/google:
    get:
      description: Sign in with google
      responses:
        "302":
          description: Found
        "307":
          description: Temporary Redirect
      summary: Sign in with google
      tags:
      - auth
  /auth/logout:
    get:
      description: Logout user
      responses:
        "200":
          description: OK
      summary: Logout user
      tags:
      - auth
  /auth/onboarding:
    post:
      consumes:
      - multipart/form-data
      description: Onboard users
      parameters:
      - description: display name
        in: formData
        name: display_name
        required: true
        type: string
      - description: about
        in: formData
        name: about
        type: string
      - description: profile_picture
        in: formData
        name: image
        type: file
      - description: app_session=12345
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            Set-Cookie:
              description: access_token=12345 refresh_token=12345
              type: string
          schema:
            $ref: '#/definitions/main.handleAuthOnboarding.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.errorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/main.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.errorResponse'
      summary: Onboard users
      tags:
      - auth
  /auth/refresh-token:
    get:
      description: Get new access token
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.handleAuthRefreshToken.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/main.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.errorResponse'
      summary: Refresh token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user using email and password
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.handleAuthRegister.request'
      produces:
      - application/json
      responses:
        "302":
          description: Found
          headers:
            Set-Cookie:
              description: app_session
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/main.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.errorResponse'
      summary: Register user
      tags:
      - auth
swagger: "2.0"
