basePath: /api/v1
definitions:
  models.ApproveBookParam:
    properties:
      approve:
        type: boolean
    required:
    - approve
    type: object
  models.ChaptersBookPreview:
    properties:
      created_at:
        type: string
      title:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.HandleGetBookResponse:
    properties:
      chapters:
        items:
          $ref: '#/definitions/models.ChaptersBookPreview'
        type: array
      description:
        type: string
      genres:
        items:
          type: string
        type: array
      image:
        type: string
      name:
        type: string
      no_of_chapters:
        type: integer
      rating:
        type: integer
      release_schedule:
        items:
          $ref: '#/definitions/models.Schedule'
        type: array
      views:
        type: integer
    type: object
  models.HandleGetBooksBooks:
    properties:
      description:
        type: string
      genres:
        items:
          type: string
        type: array
      image:
        type: string
      name:
        type: string
      no_of_chapters:
        type: integer
      rating:
        type: integer
      release_schedule:
        items:
          $ref: '#/definitions/models.Schedule'
        type: array
      views:
        type: integer
    type: object
  models.HandleGetBooksResponse:
    properties:
      books:
        items:
          $ref: '#/definitions/models.HandleGetBooksBooks'
        type: array
    type: object
  models.HandleGetBooksResponseBook:
    properties:
      approved:
        type: boolean
      completed:
        type: boolean
      created_at:
        type: string
      description:
        type: string
      genres:
        items:
          type: string
        type: array
      id:
        type: string
      image:
        type: string
      language:
        type: string
      name:
        type: string
      no_of_chapters:
        type: integer
      release_schedule:
        items:
          $ref: '#/definitions/models.Schedule'
        type: array
      updated_at:
        type: string
      views:
        type: integer
    type: object
  models.HandleGetBooksStatsResponse:
    properties:
      books:
        items:
          $ref: '#/definitions/models.HandleGetBooksResponseBook'
        type: array
    type: object
  models.HandleGetRecentReadsResponse:
    properties:
      books:
        items:
          $ref: '#/definitions/models.RecentReadsResponseBooks'
        type: array
    type: object
  models.HandleLoginParams:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    type: object
  models.HandleRegisterParams:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  models.HandleRegisterResponse:
    properties:
      id:
        type: string
    type: object
  models.HandleUploadBooksResponse:
    properties:
      id:
        type: string
    type: object
  models.MarkAsCompleteParam:
    properties:
      completed:
        type: boolean
    required:
    - completed
    type: object
  models.RecentReadsResponseBooks:
    properties:
      image:
        type: string
      last_read:
        type: string
      last_read_chapter:
        type: integer
      name:
        type: string
    type: object
  models.Schedule:
    properties:
      chapters:
        type: integer
      day:
        type: string
    required:
    - chapters
    - day
    type: object
host: localhost:8080
info:
  contact: {}
  title: Pagesy
  version: "1.0"
paths:
  /auth/google:
    get:
      description: Sign in with google
      responses:
        "302":
          description: Found
        "307":
          description: Temporary Redirect
      summary: Sign in with google
      tags:
      - auth
  /auth/google/callback:
    get:
      description: Google auth callback url
      responses:
        "302":
          description: Found
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Google auth callback url
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login using either email, username or both and password
      parameters:
      - description: user credentials
        in: body
        name: user_credentials
        required: true
        schema:
          $ref: '#/definitions/models.HandleLoginParams'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          headers:
            Set-Cookie:
              description: access_token=12345 refresh_token=12345
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Login
      tags:
      - auth
  /auth/onboarding:
    post:
      consumes:
      - multipart/form-data
      description: Onboard users with display_name, name, about and image
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: display name
        in: formData
        name: display_name
        required: true
        type: string
      - description: about
        in: formData
        name: about
        type: string
      - description: profile_picture
        in: formData
        name: image
        type: file
      - description: app_session=12345
        in: header
        name: Cookie
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            Set-Cookie:
              description: access_token=12345 refresh_token=12345
              type: string
          schema:
            $ref: '#/definitions/models.HandleRegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Onboard users
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user using email, username and password
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.HandleRegisterParams'
      produces:
      - application/json
      responses:
        "302":
          description: Found
          headers:
            Set-Cookie:
              description: app_session
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Register user
      tags:
      - auth
  /books:
    get:
      description: Get books by genre, language, both or get all books
      parameters:
      - description: book genres
        in: query
        name: genre
        type: string
      - description: book language
        in: query
        name: language
        type: string
      - description: offset number
        in: query
        name: offset
        type: string
      - description: limit number
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HandleGetBooksResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get books
      tags:
      - books
    post:
      consumes:
      - multipart/form-data
      description: Uploads a book with metadata, schedule, draft chapter, and book
        cover image
      parameters:
      - description: Book name
        in: formData
        name: name
        required: true
        type: string
      - description: Book description
        in: formData
        name: description
        required: true
        type: string
      - collectionFormat: csv
        description: Genre
        in: formData
        items:
          type: string
        name: genre
        required: true
        type: array
      - description: Book language
        in: formData
        name: language
        required: true
        type: string
      - description: Draft chapter title
        in: formData
        name: chapter_title
        required: true
        type: string
      - description: Draft chapter content
        in: formData
        name: chapter_content
        required: true
        type: string
      - collectionFormat: csv
        description: Release days (e.g. Monday, Tuesday)
        in: formData
        items:
          type: string
        name: release_schedule_day
        required: true
        type: array
      - collectionFormat: csv
        description: Chapters per day (e.g. 1, 2)
        in: formData
        items:
          type: integer
        name: release_schedule_chapter
        required: true
        type: array
      - description: Book cover image (max 3MB)
        in: formData
        name: book_cover
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.HandleUploadBooksResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Upload a new book
      tags:
      - books
  /books/{bookId}:
    delete:
      description: Delete book by id
      parameters:
      - description: book id
        in: path
        name: bookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete book
      tags:
      - books
    get:
      description: Get book by id
      parameters:
      - description: book id
        in: path
        name: bookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HandleGetBookResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get book
      tags:
      - books
    patch:
      consumes:
      - multipart/form-data
      description: Edit book name, image, description, genre or release schedule
      parameters:
      - description: Book Id
        in: path
        name: bookId
        required: true
        type: string
      - description: Book name
        in: formData
        name: name
        type: string
      - description: Book Description
        in: formData
        name: description
        type: string
      - description: Book Image
        in: formData
        name: image
        type: string
      - collectionFormat: csv
        description: Book Genres
        in: formData
        items:
          type: string
        name: genres
        type: array
      - collectionFormat: csv
        description: Release schedule days
        in: formData
        items:
          type: string
        name: release_schedule_day
        type: array
      - collectionFormat: csv
        description: Release schedule chapters
        in: formData
        items:
          type: string
        name: release_schedule_chapter
        type: array
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Edit book details
      tags:
      - books
  /books/{bookId}/approval:
    patch:
      description: Approve book by id
      parameters:
      - description: Book ID
        in: path
        name: bookId
        required: true
        type: string
      - description: Approve book body
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.ApproveBookParam'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Approve book
      tags:
      - books
  /books/{bookId}/complete:
    patch:
      description: Mark book as complete using id
      parameters:
      - description: Book ID
        in: path
        name: bookId
        required: true
        type: string
      - description: Mark book as complete body
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.MarkAsCompleteParam'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Mark book as complete
      tags:
      - books
  /books/new:
    get:
      description: Get newly updated books
      parameters:
      - description: offset number
        in: query
        name: offset
        required: true
        type: string
      - description: limit number
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HandleGetBooksResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get newly updated books
      tags:
      - books
  /books/recents:
    get:
      description: Get user's recent reads
      parameters:
      - description: offset
        in: query
        name: offset
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HandleGetRecentReadsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get recent reads
      tags:
      - books
  /books/stats:
    get:
      description: Get all books by id
      parameters:
      - description: creator id
        in: query
        name: creator_id
        type: string
      - description: offset
        in: query
        name: offset
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HandleGetBooksStatsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get books stats
      tags:
      - books
swagger: "2.0"
